# Generated by Django 5.0 on 2023-12-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='newuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('Email1', models.EmailField(max_length=100)),
                ('Password1', models.CharField(max_length=100)),
                ('Password2', models.CharField(max_length=100)),
            ],
        ),
    ]
