# Generated by Django 5.0 on 2024-01-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='forgot_password_token',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
