# Generated by Django 5.0 on 2024-01-27 15:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0003_newuser_forgot_password_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='token_created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
